### ISSUE TITLE
Type error in Menu.tsx

### ISSUE THREAD

**Issue by ge9** [kurgm/gwv-view#10]
Menu.tsxのところで型エラーが出ました。

```
ERROR in /some/folder/gwv-view/src/ui/Menu.tsx
./src/ui/Menu.tsx 58:7-16
[tsl] ERROR in /some/folder/gwv-view/src/ui/Menu.tsx(58,8)
      TS2741: Property 'placeholder' is missing in type '{ key: string; to: string; primaryText: string; leftIcon: Element; selected: boolean; dense: boolean | undefined; }' but required in type 'Pick<MenuItemLinkProps, "replace" | "slot" | "style" | "title" | "children" | "action" | "primaryText" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 278 more ... | "tooltipProps">'.


ERROR in /some/folder/gwv-view/src/ui/Menu.tsx
./src/ui/Menu.tsx 70:4-13
[tsl] ERROR in /some/folder/gwv-view/src/ui/Menu.tsx(70,5)
      TS2741: Property 'placeholder' is missing in type '{ to: string; primaryText: string; leftIcon: Element; selected: boolean; dense: boolean | undefined; }' but required in type 'Pick<MenuItemLinkProps, "replace" | "slot" | "style" | "title" | "children" | "action" | "primaryText" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 278 more ... | "tooltipProps">'.
```
原因はわかりませんが以前は出ていなかったので依存パッケージの仕様変更とかが原因なのかもしれないです。
`placeholder="test"`
みたいなのを<Menu.Item />の中に追加したらとりあえず治りました。

**Comment by kurgm** [comment]
エラーのご報告ありがとうございます！
手元でもCIでもビルドに成功（下記参照）しており，こちらでは再現できていないので，いくつか質問をさせてください。
https://github.com/kurgm/gwv-view/actions/runs/7337268864/job/19977899043?pr=11

- Node.jsのバージョンはいくつですか。（コマンド `node -v` で確認できます）
- TypeScriptのバージョンはいくつですか。（コマンド `npx tsc -v` で確認できます）
- ビルドを試みているバージョンの，コミットのハッシュはいくつですか。（`gwv-view` ディレクトリ下で コマンド `git rev-parse HEAD` で確認できます）
- コマンド `npm install` を実行してからビルドコマンド `npm build` を実行しても同じ結果になりますか。

**Comment by ge9** [comment]
コミット番号は最新の
2a008bdb036676a53aa87e1f99b87b435618847a
です。
```
git clone https://github.com/kurgm/gwv-view
cd gwv-view
npm i
npx tsc -v
npm run build
```
で確認しています。
node/npm/tscのバージョン及びOSは、
v14.19.3 / 6.14.17 / Version 5.3.3 / Linux
v14.21.3 / 6.14.18 / Version 5.3.3 / Mac
です。
一方で、そちらではちゃんと動いているとのことなのでv16.20.2やv19.3.0を試したら、このエラーは出ませんでした。
自分が今使っているLinuxサーバーでは依存ライブラリの関係の関係で18は入れられなかったのですが、16なら動いたので、とりあえず手元でも一応解決はしました。
もし14で動かないことがそちらでも確認できて、それでは良くないということになったら直していただけるとありがたいです。

**Comment by kurgm** [comment]
情報ありがとうございます。Node.js v14.21.3 + npm v6.14.18 でエラーを再現することができました。

さっそく原因についてですが， `npm install` を実行したときに以下の警告が出ていました。 [`package-lock.json` の `lockfileVersion`](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json#lockfileversion) `3` が npm v6 には互換性がないようです。
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
```
その結果， `package-lock.json` による依存パッケージのバージョン固定が効かず，（semver で指定される制約の範囲内で）最新バージョンの依存パッケージがインストールされることで問題が生じていると考えられます。

（その証拠に， Node.js v20 で `npm upgrade` を実施してからビルドを試すと， `src/ui/Menu.tsx` で同じエラーが発生しました。）

同じ Node.js v14.21.3 環境で，npm を v9.9.2 （Node.js v14 をサポートする最新のバージョン）に上げて試すと， `package-lock.json` に沿ったバージョンの依存パッケージがインストールされ，ビルドが成功しました。

----

ご指摘のように依存パッケージの仕様変更が原因のようで，将来的に依存パッケージのバージョンを上げる際にご提案のように修正する必要がありそうです。

しかし，新しい Node.js（正確には新しい npm）を使うことでビルドは成功するようですし，残念ながら古い Node.js でのビルドをサポートする予定は無いため，このissueは一旦閉じようと思います。

**Comment by ge9** [comment]
なるほど、そういう仕組みだったんですね。ありがとうございます。
